// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.collett.pulumi.rockset.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RocksetUserState extends com.pulumi.resources.ResourceArgs {

    public static final RocksetUserState Empty = new RocksetUserState();

    /**
     * The ISO-8601 time of when the user was created.
     * 
     */
    @Import(name="createdAt")
    private @Nullable Output<String> createdAt;

    /**
     * @return The ISO-8601 time of when the user was created.
     * 
     */
    public Optional<Output<String>> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }

    /**
     * Email address of the user. Also used to identify the user.
     * 
     */
    @Import(name="email")
    private @Nullable Output<String> email;

    /**
     * @return Email address of the user. Also used to identify the user.
     * 
     */
    public Optional<Output<String>> email() {
        return Optional.ofNullable(this.email);
    }

    /**
     * User&#39;s first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
     * 
     */
    @Import(name="firstName")
    private @Nullable Output<String> firstName;

    /**
     * @return User&#39;s first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
     * 
     */
    public Optional<Output<String>> firstName() {
        return Optional.ofNullable(this.firstName);
    }

    /**
     * User&#39;s last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
     * 
     */
    @Import(name="lastName")
    private @Nullable Output<String> lastName;

    /**
     * @return User&#39;s last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
     * 
     */
    public Optional<Output<String>> lastName() {
        return Optional.ofNullable(this.lastName);
    }

    /**
     * List of roles for the user. E.g. &#39;admin&#39;, &#39;member&#39;, &#39;read-only&#39;.
     * 
     */
    @Import(name="roles")
    private @Nullable Output<List<String>> roles;

    /**
     * @return List of roles for the user. E.g. &#39;admin&#39;, &#39;member&#39;, &#39;read-only&#39;.
     * 
     */
    public Optional<Output<List<String>>> roles() {
        return Optional.ofNullable(this.roles);
    }

    /**
     * State of the user, either NEW or ACTIVE.
     * 
     */
    @Import(name="state")
    private @Nullable Output<String> state;

    /**
     * @return State of the user, either NEW or ACTIVE.
     * 
     */
    public Optional<Output<String>> state() {
        return Optional.ofNullable(this.state);
    }

    private RocksetUserState() {}

    private RocksetUserState(RocksetUserState $) {
        this.createdAt = $.createdAt;
        this.email = $.email;
        this.firstName = $.firstName;
        this.lastName = $.lastName;
        this.roles = $.roles;
        this.state = $.state;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RocksetUserState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RocksetUserState $;

        public Builder() {
            $ = new RocksetUserState();
        }

        public Builder(RocksetUserState defaults) {
            $ = new RocksetUserState(Objects.requireNonNull(defaults));
        }

        /**
         * @param createdAt The ISO-8601 time of when the user was created.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(@Nullable Output<String> createdAt) {
            $.createdAt = createdAt;
            return this;
        }

        /**
         * @param createdAt The ISO-8601 time of when the user was created.
         * 
         * @return builder
         * 
         */
        public Builder createdAt(String createdAt) {
            return createdAt(Output.of(createdAt));
        }

        /**
         * @param email Email address of the user. Also used to identify the user.
         * 
         * @return builder
         * 
         */
        public Builder email(@Nullable Output<String> email) {
            $.email = email;
            return this;
        }

        /**
         * @param email Email address of the user. Also used to identify the user.
         * 
         * @return builder
         * 
         */
        public Builder email(String email) {
            return email(Output.of(email));
        }

        /**
         * @param firstName User&#39;s first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
         * 
         * @return builder
         * 
         */
        public Builder firstName(@Nullable Output<String> firstName) {
            $.firstName = firstName;
            return this;
        }

        /**
         * @param firstName User&#39;s first name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
         * 
         * @return builder
         * 
         */
        public Builder firstName(String firstName) {
            return firstName(Output.of(firstName));
        }

        /**
         * @param lastName User&#39;s last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
         * 
         * @return builder
         * 
         */
        public Builder lastName(@Nullable Output<String> lastName) {
            $.lastName = lastName;
            return this;
        }

        /**
         * @param lastName User&#39;s last name. This can only be set once the state is ACTIVE, i.e after the user has accepted the invite.
         * 
         * @return builder
         * 
         */
        public Builder lastName(String lastName) {
            return lastName(Output.of(lastName));
        }

        /**
         * @param roles List of roles for the user. E.g. &#39;admin&#39;, &#39;member&#39;, &#39;read-only&#39;.
         * 
         * @return builder
         * 
         */
        public Builder roles(@Nullable Output<List<String>> roles) {
            $.roles = roles;
            return this;
        }

        /**
         * @param roles List of roles for the user. E.g. &#39;admin&#39;, &#39;member&#39;, &#39;read-only&#39;.
         * 
         * @return builder
         * 
         */
        public Builder roles(List<String> roles) {
            return roles(Output.of(roles));
        }

        /**
         * @param roles List of roles for the user. E.g. &#39;admin&#39;, &#39;member&#39;, &#39;read-only&#39;.
         * 
         * @return builder
         * 
         */
        public Builder roles(String... roles) {
            return roles(List.of(roles));
        }

        /**
         * @param state State of the user, either NEW or ACTIVE.
         * 
         * @return builder
         * 
         */
        public Builder state(@Nullable Output<String> state) {
            $.state = state;
            return this;
        }

        /**
         * @param state State of the user, either NEW or ACTIVE.
         * 
         * @return builder
         * 
         */
        public Builder state(String state) {
            return state(Output.of(state));
        }

        public RocksetUserState build() {
            return $;
        }
    }

}
