# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['RocksetAliasArgs', 'RocksetAlias']

@pulumi.input_type
class RocksetAliasArgs:
    def __init__(__self__, *,
                 collections: pulumi.Input[str],
                 workspace: pulumi.Input[str],
                 description: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a RocksetAlias resource.
        :param pulumi.Input[str] collections: List of collections for this alias to refer to.
        :param pulumi.Input[str] workspace: Name of the workspace the alias will be in.
        :param pulumi.Input[str] description: Text describing the alias.
        :param pulumi.Input[str] name: Unique identifier for the alias. Can contain alphanumeric or dash characters.
        """
        pulumi.set(__self__, "collections", collections)
        pulumi.set(__self__, "workspace", workspace)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def collections(self) -> pulumi.Input[str]:
        """
        List of collections for this alias to refer to.
        """
        return pulumi.get(self, "collections")

    @collections.setter
    def collections(self, value: pulumi.Input[str]):
        pulumi.set(self, "collections", value)

    @property
    @pulumi.getter
    def workspace(self) -> pulumi.Input[str]:
        """
        Name of the workspace the alias will be in.
        """
        return pulumi.get(self, "workspace")

    @workspace.setter
    def workspace(self, value: pulumi.Input[str]):
        pulumi.set(self, "workspace", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        Text describing the alias.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Unique identifier for the alias. Can contain alphanumeric or dash characters.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)


@pulumi.input_type
class _RocksetAliasState:
    def __init__(__self__, *,
                 collections: Optional[pulumi.Input[str]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 workspace: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering RocksetAlias resources.
        :param pulumi.Input[str] collections: List of collections for this alias to refer to.
        :param pulumi.Input[str] description: Text describing the alias.
        :param pulumi.Input[str] name: Unique identifier for the alias. Can contain alphanumeric or dash characters.
        :param pulumi.Input[str] workspace: Name of the workspace the alias will be in.
        """
        if collections is not None:
            pulumi.set(__self__, "collections", collections)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if workspace is not None:
            pulumi.set(__self__, "workspace", workspace)

    @property
    @pulumi.getter
    def collections(self) -> Optional[pulumi.Input[str]]:
        """
        List of collections for this alias to refer to.
        """
        return pulumi.get(self, "collections")

    @collections.setter
    def collections(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "collections", value)

    @property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[str]]:
        """
        Text describing the alias.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "description", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        Unique identifier for the alias. Can contain alphanumeric or dash characters.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter
    def workspace(self) -> Optional[pulumi.Input[str]]:
        """
        Name of the workspace the alias will be in.
        """
        return pulumi.get(self, "workspace")

    @workspace.setter
    def workspace(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "workspace", value)


class RocksetAlias(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 collections: Optional[pulumi.Input[str]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 workspace: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Manages an alias for a set of collections.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] collections: List of collections for this alias to refer to.
        :param pulumi.Input[str] description: Text describing the alias.
        :param pulumi.Input[str] name: Unique identifier for the alias. Can contain alphanumeric or dash characters.
        :param pulumi.Input[str] workspace: Name of the workspace the alias will be in.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RocksetAliasArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages an alias for a set of collections.

        :param str resource_name: The name of the resource.
        :param RocksetAliasArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RocksetAliasArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 collections: Optional[pulumi.Input[str]] = None,
                 description: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 workspace: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RocksetAliasArgs.__new__(RocksetAliasArgs)

            if collections is None and not opts.urn:
                raise TypeError("Missing required property 'collections'")
            __props__.__dict__["collections"] = collections
            __props__.__dict__["description"] = description
            __props__.__dict__["name"] = name
            if workspace is None and not opts.urn:
                raise TypeError("Missing required property 'workspace'")
            __props__.__dict__["workspace"] = workspace
        super(RocksetAlias, __self__).__init__(
            'rockset:index/rocksetAlias:RocksetAlias',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            collections: Optional[pulumi.Input[str]] = None,
            description: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            workspace: Optional[pulumi.Input[str]] = None) -> 'RocksetAlias':
        """
        Get an existing RocksetAlias resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] collections: List of collections for this alias to refer to.
        :param pulumi.Input[str] description: Text describing the alias.
        :param pulumi.Input[str] name: Unique identifier for the alias. Can contain alphanumeric or dash characters.
        :param pulumi.Input[str] workspace: Name of the workspace the alias will be in.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RocksetAliasState.__new__(_RocksetAliasState)

        __props__.__dict__["collections"] = collections
        __props__.__dict__["description"] = description
        __props__.__dict__["name"] = name
        __props__.__dict__["workspace"] = workspace
        return RocksetAlias(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def collections(self) -> pulumi.Output[str]:
        """
        List of collections for this alias to refer to.
        """
        return pulumi.get(self, "collections")

    @property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[str]]:
        """
        Text describing the alias.
        """
        return pulumi.get(self, "description")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        Unique identifier for the alias. Can contain alphanumeric or dash characters.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def workspace(self) -> pulumi.Output[str]:
        """
        Name of the workspace the alias will be in.
        """
        return pulumi.get(self, "workspace")

