// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.collett.pulumi.rockset;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.collett.pulumi.rockset.RocksetQueryLambdaArgs;
import io.collett.pulumi.rockset.Utilities;
import io.collett.pulumi.rockset.inputs.RocksetQueryLambdaState;
import io.collett.pulumi.rockset.outputs.RocksetQueryLambdaSql;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a Rockset Query Lambda.
 * 
 */
@ResourceType(type="rockset:index/rocksetQueryLambda:RocksetQueryLambda")
public class RocksetQueryLambda extends com.pulumi.resources.CustomResource {
    /**
     * Text describing the query lambda.
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    /**
     * @return Text describing the query lambda.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    @Export(name="sqls", refs={List.class,RocksetQueryLambdaSql.class}, tree="[0,1]")
    private Output<List<RocksetQueryLambdaSql>> sqls;

    public Output<List<RocksetQueryLambdaSql>> sqls() {
        return this.sqls;
    }
    /**
     * The latest state of this query lambda.
     * 
     */
    @Export(name="state", refs={String.class}, tree="[0]")
    private Output<String> state;

    /**
     * @return The latest state of this query lambda.
     * 
     */
    public Output<String> state() {
        return this.state;
    }
    /**
     * The latest version string of this query lambda.
     * 
     */
    @Export(name="version", refs={String.class}, tree="[0]")
    private Output<String> version;

    /**
     * @return The latest version string of this query lambda.
     * 
     */
    public Output<String> version() {
        return this.version;
    }
    /**
     * The name of the workspace.
     * 
     */
    @Export(name="workspace", refs={String.class}, tree="[0]")
    private Output<String> workspace;

    /**
     * @return The name of the workspace.
     * 
     */
    public Output<String> workspace() {
        return this.workspace;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RocksetQueryLambda(String name) {
        this(name, RocksetQueryLambdaArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RocksetQueryLambda(String name, RocksetQueryLambdaArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RocksetQueryLambda(String name, RocksetQueryLambdaArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("rockset:index/rocksetQueryLambda:RocksetQueryLambda", name, args == null ? RocksetQueryLambdaArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private RocksetQueryLambda(String name, Output<String> id, @Nullable RocksetQueryLambdaState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("rockset:index/rocksetQueryLambda:RocksetQueryLambda", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RocksetQueryLambda get(String name, Output<String> id, @Nullable RocksetQueryLambdaState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RocksetQueryLambda(name, id, state, options);
    }
}
