// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.collett.pulumi.rockset;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RocksetApiKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final RocksetApiKeyArgs Empty = new RocksetApiKeyArgs();

    /**
     * Name of the api key.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the api key.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The role the api key will use. If not specified, &#34;All User Assigned Roles&#34; will be used.
     * 
     */
    @Import(name="role")
    private @Nullable Output<String> role;

    /**
     * @return The role the api key will use. If not specified, &#34;All User Assigned Roles&#34; will be used.
     * 
     */
    public Optional<Output<String>> role() {
        return Optional.ofNullable(this.role);
    }

    private RocksetApiKeyArgs() {}

    private RocksetApiKeyArgs(RocksetApiKeyArgs $) {
        this.name = $.name;
        this.role = $.role;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RocksetApiKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RocksetApiKeyArgs $;

        public Builder() {
            $ = new RocksetApiKeyArgs();
        }

        public Builder(RocksetApiKeyArgs defaults) {
            $ = new RocksetApiKeyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Name of the api key.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the api key.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param role The role the api key will use. If not specified, &#34;All User Assigned Roles&#34; will be used.
         * 
         * @return builder
         * 
         */
        public Builder role(@Nullable Output<String> role) {
            $.role = role;
            return this;
        }

        /**
         * @param role The role the api key will use. If not specified, &#34;All User Assigned Roles&#34; will be used.
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            return role(Output.of(role));
        }

        public RocksetApiKeyArgs build() {
            return $;
        }
    }

}
