// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.collett.pulumi.rockset;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.collett.pulumi.rockset.RocksetWorkspaceArgs;
import io.collett.pulumi.rockset.Utilities;
import io.collett.pulumi.rockset.inputs.RocksetWorkspaceState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a Rockset workspace.
 * 
 */
@ResourceType(type="rockset:index/rocksetWorkspace:RocksetWorkspace")
public class RocksetWorkspace extends com.pulumi.resources.CustomResource {
    /**
     * The user who created the workspace.
     * 
     */
    @Export(name="createdBy", type=String.class, parameters={})
    private Output<String> createdBy;

    /**
     * @return The user who created the workspace.
     * 
     */
    public Output<String> createdBy() {
        return this.createdBy;
    }
    /**
     * Text describing the collection.
     * 
     */
    @Export(name="description", type=String.class, parameters={})
    private Output</* @Nullable */ String> description;

    /**
     * @return Text describing the collection.
     * 
     */
    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    /**
     * Unique identifier for workspace. Can contain alphanumeric or dash characters.
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return Unique identifier for workspace. Can contain alphanumeric or dash characters.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RocksetWorkspace(String name) {
        this(name, RocksetWorkspaceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RocksetWorkspace(String name, @Nullable RocksetWorkspaceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RocksetWorkspace(String name, @Nullable RocksetWorkspaceArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("rockset:index/rocksetWorkspace:RocksetWorkspace", name, args == null ? RocksetWorkspaceArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private RocksetWorkspace(String name, Output<String> id, @Nullable RocksetWorkspaceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("rockset:index/rocksetWorkspace:RocksetWorkspace", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static RocksetWorkspace get(String name, Output<String> id, @Nullable RocksetWorkspaceState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new RocksetWorkspace(name, id, state, options);
    }
}
