// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Collett.Rockset.Outputs
{

    [OutputType]
    public sealed class RocksetGcsCollectionSource
    {
        /// <summary>
        /// GCS bucket containing the target data.
        /// </summary>
        public readonly string Bucket;
        public readonly Outputs.RocksetGcsCollectionSourceCsv? Csv;
        /// <summary>
        /// Format of the data. One of: json, csv, xml. xml and csv blocks can only be set for their respective formats.
        /// </summary>
        public readonly string Format;
        /// <summary>
        /// The name of the Rockset GCS integration.
        /// </summary>
        public readonly string IntegrationName;
        /// <summary>
        /// Simple path prefix to GCS key.
        /// </summary>
        public readonly string? Prefix;
        public readonly Outputs.RocksetGcsCollectionSourceXml? Xml;

        [OutputConstructor]
        private RocksetGcsCollectionSource(
            string bucket,

            Outputs.RocksetGcsCollectionSourceCsv? csv,

            string format,

            string integrationName,

            string? prefix,

            Outputs.RocksetGcsCollectionSourceXml? xml)
        {
            Bucket = bucket;
            Csv = csv;
            Format = format;
            IntegrationName = integrationName;
            Prefix = prefix;
            Xml = xml;
        }
    }
}
