// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.collett.pulumi.rockset.outputs;

import com.pulumi.core.annotations.CustomType;
import io.collett.pulumi.rockset.outputs.RocksetS3CollectionSourceCsv;
import io.collett.pulumi.rockset.outputs.RocksetS3CollectionSourceXml;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class RocksetS3CollectionSource {
    /**
     * @return S3 bucket containing the target data.
     * 
     */
    private String bucket;
    private @Nullable RocksetS3CollectionSourceCsv csv;
    /**
     * @return Format of the data. One of: json, csv, xml. xml and csv blocks can only be set for their respective formats.
     * 
     */
    private String format;
    /**
     * @return The name of the Rockset S3 integration. If no S3 integration is provided only data in public S3 buckets are accessible.
     * 
     */
    private String integrationName;
    /**
     * @return Regex path pattern to S3 keys.
     * 
     */
    private @Nullable String pattern;
    /**
     * @return Simple path prefix to S3 keys.
     * 
     * @deprecated
     * use pattern instead
     * 
     */
    @Deprecated /* use pattern instead */
    private @Nullable String prefix;
    private @Nullable RocksetS3CollectionSourceXml xml;

    private RocksetS3CollectionSource() {}
    /**
     * @return S3 bucket containing the target data.
     * 
     */
    public String bucket() {
        return this.bucket;
    }
    public Optional<RocksetS3CollectionSourceCsv> csv() {
        return Optional.ofNullable(this.csv);
    }
    /**
     * @return Format of the data. One of: json, csv, xml. xml and csv blocks can only be set for their respective formats.
     * 
     */
    public String format() {
        return this.format;
    }
    /**
     * @return The name of the Rockset S3 integration. If no S3 integration is provided only data in public S3 buckets are accessible.
     * 
     */
    public String integrationName() {
        return this.integrationName;
    }
    /**
     * @return Regex path pattern to S3 keys.
     * 
     */
    public Optional<String> pattern() {
        return Optional.ofNullable(this.pattern);
    }
    /**
     * @return Simple path prefix to S3 keys.
     * 
     * @deprecated
     * use pattern instead
     * 
     */
    @Deprecated /* use pattern instead */
    public Optional<String> prefix() {
        return Optional.ofNullable(this.prefix);
    }
    public Optional<RocksetS3CollectionSourceXml> xml() {
        return Optional.ofNullable(this.xml);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RocksetS3CollectionSource defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String bucket;
        private @Nullable RocksetS3CollectionSourceCsv csv;
        private String format;
        private String integrationName;
        private @Nullable String pattern;
        private @Nullable String prefix;
        private @Nullable RocksetS3CollectionSourceXml xml;
        public Builder() {}
        public Builder(RocksetS3CollectionSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.bucket = defaults.bucket;
    	      this.csv = defaults.csv;
    	      this.format = defaults.format;
    	      this.integrationName = defaults.integrationName;
    	      this.pattern = defaults.pattern;
    	      this.prefix = defaults.prefix;
    	      this.xml = defaults.xml;
        }

        @CustomType.Setter
        public Builder bucket(String bucket) {
            this.bucket = Objects.requireNonNull(bucket);
            return this;
        }
        @CustomType.Setter
        public Builder csv(@Nullable RocksetS3CollectionSourceCsv csv) {
            this.csv = csv;
            return this;
        }
        @CustomType.Setter
        public Builder format(String format) {
            this.format = Objects.requireNonNull(format);
            return this;
        }
        @CustomType.Setter
        public Builder integrationName(String integrationName) {
            this.integrationName = Objects.requireNonNull(integrationName);
            return this;
        }
        @CustomType.Setter
        public Builder pattern(@Nullable String pattern) {
            this.pattern = pattern;
            return this;
        }
        @CustomType.Setter
        public Builder prefix(@Nullable String prefix) {
            this.prefix = prefix;
            return this;
        }
        @CustomType.Setter
        public Builder xml(@Nullable RocksetS3CollectionSourceXml xml) {
            this.xml = xml;
            return this;
        }
        public RocksetS3CollectionSource build() {
            final var o = new RocksetS3CollectionSource();
            o.bucket = bucket;
            o.csv = csv;
            o.format = format;
            o.integrationName = integrationName;
            o.pattern = pattern;
            o.prefix = prefix;
            o.xml = xml;
            return o;
        }
    }
}
