// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Collett.Rockset.Inputs
{

    public sealed class RocksetQueryLambdaSqlDefaultParameterGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public RocksetQueryLambdaSqlDefaultParameterGetArgs()
        {
        }
        public static new RocksetQueryLambdaSqlDefaultParameterGetArgs Empty => new RocksetQueryLambdaSqlDefaultParameterGetArgs();
    }
}
