// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages a Rockset Query Lambda.
 */
export class RocksetQueryLambda extends pulumi.CustomResource {
    /**
     * Get an existing RocksetQueryLambda resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RocksetQueryLambdaState, opts?: pulumi.CustomResourceOptions): RocksetQueryLambda {
        return new RocksetQueryLambda(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'rockset:index/rocksetQueryLambda:RocksetQueryLambda';

    /**
     * Returns true if the given object is an instance of RocksetQueryLambda.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RocksetQueryLambda {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RocksetQueryLambda.__pulumiType;
    }

    /**
     * Text describing the query lambda.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
     */
    public readonly name!: pulumi.Output<string>;
    public readonly sqls!: pulumi.Output<outputs.RocksetQueryLambdaSql[]>;
    /**
     * The latest state of this query lambda.
     */
    public /*out*/ readonly state!: pulumi.Output<string>;
    /**
     * The latest version string of this query lambda.
     */
    public /*out*/ readonly version!: pulumi.Output<string>;
    /**
     * The name of the workspace.
     */
    public readonly workspace!: pulumi.Output<string>;

    /**
     * Create a RocksetQueryLambda resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RocksetQueryLambdaArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RocksetQueryLambdaArgs | RocksetQueryLambdaState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RocksetQueryLambdaState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["sqls"] = state ? state.sqls : undefined;
            resourceInputs["state"] = state ? state.state : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
            resourceInputs["workspace"] = state ? state.workspace : undefined;
        } else {
            const args = argsOrState as RocksetQueryLambdaArgs | undefined;
            if ((!args || args.sqls === undefined) && !opts.urn) {
                throw new Error("Missing required property 'sqls'");
            }
            if ((!args || args.workspace === undefined) && !opts.urn) {
                throw new Error("Missing required property 'workspace'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["sqls"] = args ? args.sqls : undefined;
            resourceInputs["workspace"] = args ? args.workspace : undefined;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RocksetQueryLambda.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RocksetQueryLambda resources.
 */
export interface RocksetQueryLambdaState {
    /**
     * Text describing the query lambda.
     */
    description?: pulumi.Input<string>;
    /**
     * Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
     */
    name?: pulumi.Input<string>;
    sqls?: pulumi.Input<pulumi.Input<inputs.RocksetQueryLambdaSql>[]>;
    /**
     * The latest state of this query lambda.
     */
    state?: pulumi.Input<string>;
    /**
     * The latest version string of this query lambda.
     */
    version?: pulumi.Input<string>;
    /**
     * The name of the workspace.
     */
    workspace?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RocksetQueryLambda resource.
 */
export interface RocksetQueryLambdaArgs {
    /**
     * Text describing the query lambda.
     */
    description?: pulumi.Input<string>;
    /**
     * Unique identifier for the query lambda. Can contain alphanumeric or dash characters.
     */
    name?: pulumi.Input<string>;
    sqls: pulumi.Input<pulumi.Input<inputs.RocksetQueryLambdaSql>[]>;
    /**
     * The name of the workspace.
     */
    workspace: pulumi.Input<string>;
}
